/* tslint:disable */
/* eslint-disable */
/**
 * Implementing Server Side Kotlin
 * Sample API of Hands On Server Side Kotlin
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NewStaff } from './NewStaff';
import {
    NewStaffFromJSON,
    NewStaffFromJSONTyped,
    NewStaffToJSON,
} from './NewStaff';

/**
 * 新規作成するスタッフ
 * @export
 * @interface NewStaffRequest
 */
export interface NewStaffRequest {
    /**
     * 
     * @type {NewStaff}
     * @memberof NewStaffRequest
     */
    staff: NewStaff;
}

/**
 * Check if a given object implements the NewStaffRequest interface.
 */
export function instanceOfNewStaffRequest(value: object): value is NewStaffRequest {
    if (!('staff' in value) || value['staff'] === undefined) return false;
    return true;
}

export function NewStaffRequestFromJSON(json: any): NewStaffRequest {
    return NewStaffRequestFromJSONTyped(json, false);
}

export function NewStaffRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewStaffRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'staff': NewStaffFromJSON(json['staff']),
    };
}

export function NewStaffRequestToJSON(value?: NewStaffRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'staff': NewStaffToJSON(value['staff']),
    };
}

