/* tslint:disable */
/* eslint-disable */
/**
 * Implementing Server Side Kotlin
 * Sample API of Hands On Server Side Kotlin
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewStaff
 */
export interface NewStaff {
    /**
     * 名
     * @type {string}
     * @memberof NewStaff
     */
    firstName: string;
    /**
     * 性
     * @type {string}
     * @memberof NewStaff
     */
    lastName: string;
    /**
     * 生年月日
     * @type {Date}
     * @memberof NewStaff
     */
    birthDate: Date;
    /**
     * メールアドレス
     * @type {string}
     * @memberof NewStaff
     */
    email: string;
}

/**
 * Check if a given object implements the NewStaff interface.
 */
export function instanceOfNewStaff(value: object): value is NewStaff {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('birthDate' in value) || value['birthDate'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function NewStaffFromJSON(json: any): NewStaff {
    return NewStaffFromJSONTyped(json, false);
}

export function NewStaffFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewStaff {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'birthDate': (new Date(json['birthDate'])),
        'email': json['email'],
    };
}

export function NewStaffToJSON(value?: NewStaff | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'birthDate': ((value['birthDate']).toISOString()),
        'email': value['email'],
    };
}

