/* tslint:disable */
/* eslint-disable */
/**
 * Implementing Server Side Kotlin
 * Sample API of Hands On Server Side Kotlin
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateStaff } from './UpdateStaff';
import {
    UpdateStaffFromJSON,
    UpdateStaffFromJSONTyped,
    UpdateStaffToJSON,
} from './UpdateStaff';

/**
 * 
 * @export
 * @interface UpdateStaffRequest
 */
export interface UpdateStaffRequest {
    /**
     * 
     * @type {UpdateStaff}
     * @memberof UpdateStaffRequest
     */
    staff: UpdateStaff;
}

/**
 * Check if a given object implements the UpdateStaffRequest interface.
 */
export function instanceOfUpdateStaffRequest(value: object): value is UpdateStaffRequest {
    if (!('staff' in value) || value['staff'] === undefined) return false;
    return true;
}

export function UpdateStaffRequestFromJSON(json: any): UpdateStaffRequest {
    return UpdateStaffRequestFromJSONTyped(json, false);
}

export function UpdateStaffRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateStaffRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'staff': UpdateStaffFromJSON(json['staff']),
    };
}

export function UpdateStaffRequestToJSON(value?: UpdateStaffRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'staff': UpdateStaffToJSON(value['staff']),
    };
}

