import { useState } from 'react';
import { useRouter } from 'next/router';
import useSWRMutation from 'swr/mutation';
import Head from 'next/head';
import { Box, Container, Fab, Grid, TextField } from '@mui/material';
import LoadingOverlay from '@/components/LoadingOverlay';
import { pagesPath } from '@/utils/$path';
import { Save } from '@mui/icons-material';
import { NewStaff, Staff } from '@/openapi/openapi-generated';
import { format } from 'date-fns';

const fetcher = async (url: string, { arg }: { arg: NewStaff }) =>
  await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ staff: arg }),
  });

export default function Create() {
  const [staff, setStaff] = useState<Staff>({
    id: 0,
    lastName: '',
    firstName: '',
    birthDate: new Date(),
    email: '',
  });

  const router = useRouter();
  const { trigger, isMutating } = useSWRMutation(
    'http://localhost:8080/api/staffs/',
    fetcher,
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Box
            sx={(_theme) => ({
              maxWidth: '105ch',
              width: '100%',
            })}
          >
            {isMutating && <LoadingOverlay />}
            <Grid
              container
              spacing={2}
              style={{
                height: '100%',
                width: '100%',
                marginTop: 40,
              }}
            >
              <Grid item xs={12}>
                エラーメッセージ
              </Grid>

              <Grid item xs={12}>
                <TextField
                  fullWidth
                  required
                  label="姓"
                  value={staff.lastName}
                  onChange={(e) =>
                    setStaff({ ...staff, lastName: e.target.value })
                  }
                />
              </Grid>

              <Grid item xs={12}>
                <TextField
                  fullWidth
                  required
                  label="名"
                  value={staff.firstName}
                  onChange={(e) =>
                    setStaff({ ...staff, firstName: e.target.value })
                  }
                />
              </Grid>

              <Grid item xs={12}>
                <TextField
                  label="生年月日"
                  type="date"
                  value={format(staff.birthDate, 'yyyy-MM-dd')}
                  onChange={(e) => {
                    setStaff({
                      ...staff,
                      birthDate: new Date(e.target.value),
                    });
                  }}
                />
              </Grid>

              <Grid item xs={12}>
                <TextField
                  label="email"
                  type="email"
                  value={staff.email}
                  onChange={(e) => {
                    setStaff({
                      ...staff,
                      email: e.target.value,
                    });
                  }}
                />
              </Grid>
            </Grid>
            <Fab
              variant="extended"
              color="primary"
              style={{ left: '50%', bottom: '2%', position: 'fixed' }}
              disabled={isMutating}
              onClick={async () => {
                await trigger(staff);
                await router.push(pagesPath.staff.$url());
              }}
            >
              <Save />
              保存
            </Fab>
          </Box>
        </Container>
      </main>
    </>
  );
}
